# Site settings
author: Conor Hamilton
title: Coding with Conor
header-img: img/home-bg.png
email: conhamil19@gmail.com
copyright_name: Conor Hamilton
description: > # this means to ignore newlines until "baseurl:"
  My journey into the world of Software Development.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ConorHamilton19

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
